# Generated by Django 5.1.5 on 2025-02-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('1P', '1 Point'), ('2P', '2 Points'), ('3P', '3 Points'), ('FP', 'Personal foul'), ('FO', 'Other foul'), ('EX', 'Exchange'), ('TO', 'Timeout')], default='TO', max_length=2),
            preserve_default=False,
        ),
    ]
