# Generated by Django 5.1.5 on 2025-02-09 13:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0005_alter_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='startTime',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
