# Generated by Django 5.1.6 on 2025-02-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0006_match_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='startTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
