# Generated by Django 5.1.6 on 2025-02-24 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0008_match_clockpaused_match_timepaused_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p1', to='matchup.matchplayer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2', to='matchup.matchplayer'),
        ),
    ]
