# Generated by Django 5.1.6 on 2025-02-24 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0009_alter_event_player1_alter_event_player2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p1', to='matchup.matchplayer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2', to='matchup.matchplayer'),
        ),
    ]
